name: 'Jason Jani '
favicon: null
layout_spectrum: 0.48296374431811273
typography_spectrum: 0.4589817710220814
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.557613542303443
  lightness: 0.6880704378709197
  saturation: 0.6139050449710339
  rhythmicContrast: 0.7057274340186268
purpose: []
